# .gitlab-ci.yml

stages:
  - test

cache:
  paths:
    - vendor/

test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y php-cli  php-xml php-mbstring unzip curl
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --ignore-platform-req=ext-mbstring
  script:
    - ./vendor/bin/phpunit --configuration phpunit.xml