# .gitlab-ci.yml

stages:
  - verify
  - test

verify_phpunit_path:
  before_script:
    - apt-get update && apt-get install -y phpunit
  script:
    - which phpunit

test-job:
  stage: test
  before_script:
    - apt-get update && apt-get install -y php-cli php-xml
  script: 
    - php -v
    - php -d include_path=.:/usr/local/lib/php -d display_errors=On /usr/local/bin/phpunit --bootstrap login.php test/login.test.php
