# .gitlab-ci.yml

stages:
  - test

test:
  stage: test
  script:
    - apt-get update && apt-get install -y php-cli php-xml
    - php -v
    - php -d include_path=.:/usr/local/lib/php -d display_errors=On /usr/local/bin/phpunit --bootstrap login.php test/login.test.php
